flowers/urls.py
from django.urls import path

from . import views

app_name = "flowers"
urlpatterns = [
    path("all", views.plants_list, name="plants-all"),
    path('add', views.plants_add, name="add"),
    path('delete', views.plants_delete, name="delete"),
    path(r'delete/(?P<pk>\d+)', views.plants_delete_pk, name="delete"),
    path('', views.home, name="home"),
]

flowershop/urls.py
from django.contrib import admin
from django.urls import include, path
from flowers import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('plants/', include("flowers.urls")),
    path('', views.home, name="home"),
]

flowers/models.py
from django.db import models


class Shop(models.Model):
    city = models.TextField(blank=True, null=True)
    house = models.TextField(blank=True, null=True)
    postal_code = models.TextField(blank=True, null=True)
    office_hours = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'shop'

class Plant(models.Model):
    description = models.TextField(blank=True, null=True)
    image = models.TextField(blank=True, null=True)
    species = models.TextField()
    shop = models.ForeignKey('Shop', models.DO_NOTHING, blank=True, null=True)

    class Meta:
        db_table = 'plant'

flowers/forms.py
from typing import TextIO
from django import forms
from .models import Plant, Shop
from django.forms import ModelForm, TextInput


class PlantAdd(forms.ModelForm):
    class Meta:
        model = Plant
        fields = ["description", "image", "species", "shop"]
        labels = {"description": "Description", "image": "Image", "species": "Species"}
        widgets = {
            "species": TextInput(
                attrs={
                    "class": "form-control",
                    "style": "max-width: 500px; margin: 20px;",
                    "placeholder": "Name",
                }
            ),
            "description": TextInput(
                attrs={
                    "class": "form-control",
                    "style": "max-width: 500px; margin: 20px;",
                    "placeholder": "Description",
                }
            ),
            "image": TextInput(
                attrs={
                    "class": "form-control",
                    "style": "max-width: 500px; margin: 20px;",
                    "placeholder": "Image url",
                }
            ),
        }

    # def __init__(self, *args, **kwargs):
    #     shop = Shop.objects.first()
    #     self.fields["shop_id"] = shop.id

flowers/views.py
from django.shortcuts import render
from .models import Plant, Shop
from .forms import PlantAdd
from django.views.decorators.csrf import csrf_exempt


def plants_list(request):
    plants = Plant.objects.all()
    ctx = {
        "plants": plants,
    }
    return render(request, "plants.html", ctx)

def home(request):
    shop = Shop.objects.first()
    ctx = {
        "shop": shop
    }
    return render(request, "home.html", ctx)

@csrf_exempt
def plants_add(request):
    if request.method == 'POST':
        form = PlantAdd(request.POST)
        if form.is_valid():
            form.save()
            plants = Plant.objects.all()
            return render(request, "plants.html", {"plants": plants})

    else:
        form = PlantAdd()

    return render(request, 'addplant.html', {'form': form})

@csrf_exempt
def plants_delete(request):
    plants = Plant.objects.all()
    return render(request, 'deleteplant.html', {"plants": plants})

@csrf_exempt
def plants_delete_pk(request, pk):
    plants = Plant.objects.filter(pk=pk).delete()
    plants = Plant.objects.all()
    return render(request, 'deleteplant.html', {"plants": plants})
    

flowershop/templates/addplant.html
{% extends "home.html" %}
{% load static %}
{% block content %}

<div class="container">
    <h1>New plant</h1>
    <form action="{% url 'flowers:add' %}" method="post">
        {% csrf_token %}
        <div class="form-control">
            {{ form.species }}
        </div>
        <div class="form-control">
            {{ form.description }}
        </div>
        <div class="form-control">
            {{ form.image }}
        </div>
        <div class="form-control" style="margin: 20px">
            {{ form.shop }}
        </div>
        <div>
            <input class="my-button" type="submit" value="Submit">
        </div>
    </form>
</div>
{% endblock content %}

flowershop/templates/deleteplant.html
{% extends "home.html" %}
{% load static %}
{% block content %}
{% load tz %}

  <div class="grid-container">
    {% for plant in plants %}
            <div class="grid-item">
              <ul class = "plants">
                <h4> <b>{{plant.species}}</b> </a></h4>
                <h5>{{plant.description}} </h5>
                <img src = "{% static plant.image %}" alt="{{plant.species}}" style="max-width:200px; max-height: 200px;" />
                <br /><br />
              </ul>
            

                <form action="{% url 'flowers:delete' plant.pk %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Delete" class="delete-button"/>
                </form>
            </div>
    {% endfor %}
  </div>
{% endblock content %}

flowershop/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<title>Flowers shop</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
<link rel="stylesheet" href="{% static 'style.css'%}">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<body>

  <div class="topnav">
    <a class="active" href="{% url 'flowers:plants-all' %}">Home</a>
    <a href="{% url 'flowers:add' %}">Add plant</a>
    <a href="{% url 'flowers:delete' %}">Remove plant</a>
  </div>
    
    <div class="w3-container" id="content" style="margin-top:35px">
      {% block content %}

      {% endblock content %}
    </div>

</body>

</html>

flowershop/templates/plants.html
{% extends "home.html" %}
{% load static %}
{% block content %}
{% load tz %}

  <div class="grid-container">
    {% for plant in plants %}
            <div class="grid-item">
              <ul class = "plants">
                <h4> <b>{{plant.species}}</b> </a></h4>
                <h5>Description: {{plant.description}} </h5>
                <img src = "{% static plant.image %}" alt="{{plant.species}}" style="max-width:200px; max-height: 200px;" />
                <br /><br />
              </ul>
            </div>
    {% endfor %}
  </div>
{% endblock content %}